#pragma once

#define WIRELESSID_APP_NAME "WirelessID"
#define WIRELESSID_LOG_TAG "WirelessID"
#define WIRELESSID_STARTUP_BANNER "ESP32-C3 application started"

#define WIRELESSID_DEFAULT_UART0_BAUD_RATE 115200
#define WIRELESSID_DEFAULT_IR_UART_BAUD_RATE 9600
#define WIRELESSID_DEFAULT_I2C_FREQ_HZ 400000
#define WIRELESSID_DEFAULT_DISPLAY_I2C_ADDR 0x3C
#define WIRELESSID_DEFAULT_IR_CARRIER_HZ 38000
#define WIRELESSID_DEFAULT_IR_CARRIER_DUTY_PERCENT 33
#define WIRELESSID_DEFAULT_TWAI_BAUD_RATE 1000000

#define WIRELESSID_STATUS_TASK_STACK_SIZE 4096
#define WIRELESSID_STATUS_TASK_PRIORITY 5
