#pragma once

#define WIRELESSID_APP_NAME "WirelessID"
#define WIRELESSID_LOG_TAG "WirelessID"
#define WIRELESSID_STARTUP_BANNER "ESP32-C3 application started"

#define WIRELESSID_DEFAULT_UART0_BAUD_RATE 115200
#define WIRELESSID_DEFAULT_IR_UART_BAUD_RATE 4800
#define WIRELESSID_DEFAULT_I2C_FREQ_HZ 400000
#define WIRELESSID_DEFAULT_DISPLAY_I2C_ADDR 0x3C
#define WIRELESSID_DEFAULT_IR_CARRIER_HZ 38000
#define WIRELESSID_DEFAULT_IR_CARRIER_DUTY_PERCENT 33
#define WIRELESSID_DEFAULT_TWAI_BAUD_RATE 1000000

// ===== Debug/Test feature switches =====
// UART0 loopback test: RX callback echoes data back
#define WIRELESSID_UART0_LOOPBACK_TEST_ENABLE 0
// UART0 alive probe: periodically send "U0_TX_ALIVE"
#define WIRELESSID_UART0_ALIVE_PROBE_ENABLE 0
// TWAI periodic test TX in app_main loop
#define WIRELESSID_TWAI_TEST_TX_ENABLE 1
// IR TX test: periodically send test frame via infrared
#define WIRELESSID_IR_TEST_TX_ENABLE 0
// IR RX test: receive IR data and print to log
#define WIRELESSID_IR_TEST_RX_ENABLE 1

#define WIRELESSID_STATUS_TASK_STACK_SIZE 4096
#define WIRELESSID_STATUS_TASK_PRIORITY 5
